=== shiwano/master/fixtures/masterdata.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "items": {
    "additionalProperties": false,
    "properties": {
      "age": {
        "type": "number"
      },
      "gender": {
        "type": "string"
      },
      "id": {
        "type": "number"
      },
      "items": {
        "items": {
          "additionalProperties": false,
          "properties": {
            "count": {
              "type": "number"
            },
            "desc": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "sale": {
              "type": "boolean"
            }
          },
          "required": [
            "count",
            "desc",
            "name",
            "sale"
          ],
          "type": "object"
        },
        "type": "array"
      },
      "name": {
        "type": "string"
      },
      "parents": {
        "additionalProperties": false,
        "properties": {
          "father": {
            "type": "string"
          },
          "mother": {
            "type": "string"
          }
        },
        "required": [
          "father",
          "mother"
        ],
        "type": "object"
      },
      "voice_actors": {
        "items": {
          "type": "string"
        },
        "type": "array"
      }
    },
    "required": [
      "age",
      "gender",
      "id",
      "items",
      "name",
      "parents",
      "voice_actors"
    ],
    "type": "object"
  },
  "title": "masterdata.json",
  "type": "array"
}

=== shiwano/master/fixtures/masterdata.json
[
  {
    "age": 10,
    "gender": "male",
    "id": 1,
    "items": [
      {
        "count": 1,
        "desc": "ハエを叩く",
        "name": "しっぽ",
        "sale": false
      }
    ],
    "name": "ムーミン",
    "parents": {
      "father": "ムーミンパパ",
      "mother": "ムーミンママ"
    },
    "voice_actors": [
      "岸田今日子",
      "高山みなみ",
      "野島健児"
    ]
  },
  {
    "age": 15,
    "gender": "male",
    "id": 2,
    "items": [
      {
        "count": 2,
        "desc": "魚を釣る",
        "name": "釣り竿",
        "sale": true
      },
      {
        "count": 1,
        "desc": "たまに吹く",
        "name": "ハーモニカ",
        "sale": true
      }
    ],
    "name": "スナフキン",
    "parents": {
      "father": "ヨクサル",
      "mother": ""
    },
    "voice_actors": [
      "西本裕行",
      "子安武人",
      "白熊寛嗣"
    ]
  },
  {
    "age": 18,
    "gender": "female",
    "id": 3,
    "items": [
      {
        "count": 1,
        "desc": "",
        "name": "ソリ",
        "sale": true
      }
    ],
    "name": "ミイ",
    "parents": {
      "father": "",
      "mother": "ミムラ"
    },
    "voice_actors": [
      "堀絢子",
      "佐久間レイ",
      "水田わさび"
    ]
  }
]
